name: The Borg - Snyk Code Test
on: 
  pull_request:
    paths:
      - 'cell/pollerbear/rtkpollerbear/rtkpollerbear/integrations/**'
jobs:
  borg-snyk-code-test:
    runs-on: ubuntu-22.04
    permissions:
      contents: read
      security-events: write
      actions: read
    steps:
      - uses: actions/checkout@v4
      - name: The Borg - Snyk Code Test
        uses: rtkwlf-actions/snyk/python-3.9@0.4.0
        continue-on-error: true
        env:
          SNYK_TOKEN: ${{ secrets.SNYK_TOKEN }}
        with:
          command: code test
          args: --sarif-file-output=snyk.sarif
      - name: Upload result to GitHub Code Scanning
        uses: github/codeql-action/upload-sarif@v2
        with:
          sarif_file: snyk.sarif