name: The Borg - Snyk Code Test
on: 
  push:
    paths:
      - 'cell/pollerbear/rtkpollerbear/rtkpollerbear/integrations/**'
jobs:
  borg-snyk-code-test:
    runs-on: ubuntu-latest
    permissions:
      actions: read
      security-events: write    
    steps:
      - uses: actions/checkout@master
      - name: The Borg - Snyk Code Test
        uses: snyk/actions/python-3.9@master
        continue-on-error: true
        env:
          SNYK_TOKEN: ${{ secrets.SNYK_TOKEN }}
        with:
          command: code test
          args: --sarif-file-output=snyk.sarif
      - name: Upload result to GitHub Code Scanning
        uses: github/codeql-action/upload-sarif@v2
        with:
          sarif_file: snyk.sarif